name: Update Sensor Data

on:
  schedule:
    # Exécution toutes les 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:  # Permet de déclencher manuellement depuis l'onglet Actions de GitHub

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Nécessaire pour pouvoir commiter/pusher

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch sensor data and update JSON
        run: |
          # Utilisation du chemin absolu pour être sûr
          python $GITHUB_WORKSPACE/fetch_sensor_data.py
        env:
          # Utilisation de variables d'environnement pour la configuration
          ESP32_PORT: 5000
          SENSOR_TIMEOUT: 5

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json  # Ajoute le fichier de données mis à jour
          
          # Commiter seulement si des changements ont été ajoutés
          if ! git diff --staged --quiet; then
            git commit -m "Update sensor data (Automated)" -m "[skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
